sudo: required
languages: node_js
node_js:
- '6'
services:
- docker
branches:
  only:
  - master
  - stable
before_install:
- npm install -g @angular/cli
- pip install awscli
- export PATH=$PATH:$HOME/.local/bin
- pip install ecs-deploy
install:
- npm install
script:
- ng build --env=prod --output-hashing none
after_success:
- docker --version
- eval $(aws ecr get-login --no-include-email --region ap-southeast-1)
- docker build -t frontend .
- docker tag frontend:latest 956664028978.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:latest
- docker push 956664028978.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:latest
- ecs deploy maxgoh ecscompose-service-maxgoh-fullstack-service
env:
  global:
  - secure: dMB5C7QXznPvgHee/UcqB3a+cwO+/TIAnsVKprYh+G423c4hRffm52Fb0r44F7BkVW1piy9iRZ2rneJkWcaRJju8PFslXa/aVxC/78a64gO+0oopad190g4S8SmAl8jX52EtOhbxlYgAUQR9YDeCOpInmsdOyq8N4MTxZ0YaXvklth36+wS2yLexjNoPiwOr5btHBPHvnvvipmhkO3WzgZO0KVWNGHv68gJmqzsjg2xldjajzXp3S+hQqLm4wVBNMHS6d+9trrzaa8slYkgerrfs/nDziaNlHWptp4SI47EHDWX7WN/xYyIEpdWJ4mXDgA7JSWBwMbFJmbNWEzzS6Bf0rCnPrKylhFRnv8reQT/7dnzbmlXaurJhq9UCysUgHFV02XYns2jcjpHbml0jLgiyalYZ0gOrELj6SAzFW08M4ync0nhcYsl50VBKWNO0wh9IQLi52c2xqYdF0GUTEX5kvuJxsRuDOd1bF0w16YLAow27kE+2yPuORvgUYFnzCpXgXXpvU6gbeu8HxZBCzoHz0RVxzXyoYQj9QcGQJaIkHa7NAdIeimJwoeaLfU/YDIa7Sk/8GEf1GiCkmTwUqM4uIGJx+9C3ycJ1I8UE/+whYUNTY1uuNmfTPnotJ5c3ZsZg+P1yq8r1vAmj999NwrUPFj9Bl/AFqRu/gIPvYuU=
  - secure: OEqbVXKfhUIDZjD1084Rt5Hb9x8rlwtazZVwnndq10vUxKrgIGc0ZdyN0r2j8JqlL7y6iJNfJpL1w4T7H8vWa4Ew1VzWjzpqk4ea7iC1+AuF+BdbknwZp2pb4SyIZ2+07PB6Z2Lb3f3sS+XH96tfWN5v5Gzt3CC/BM6aLK4ZPcVS+QP8Q9p+r/dbyi5i3lYtlZeiwzxJXa56xqdnaRkXsk3ofCiGOXijx5pK4iot/CdMgQxisjOkiQVLa8LA3tGIYYwMmxd9r5Y3w/7JymdRfy6mDWDf3sKdJq/oouzbo5yuhw8qMTskX696TZjkYI6J99WWfO2iN+A9JjdtWImRdsfCSUxUYreDIf7PoJoKlEbC4t12ACbC9xe6FkXKkrWoavkwN2n9gZXqYf4551FI5ux1Yx2on8toMbCSsCaP6BT+iRjXdt5Z5XJnnk6PxBEBsP/T8ba4CF+KwzB/becLWa+It+skcjtQAN3VA6l7qdtiRpQo3tvzSbpbkO0J/AUCWk6niY3NYgkvNHBFWHCNgN+7p9O5+Dd9gQoyzHWtEhRhtRsL6FTlXn6ZM5rdQMsT760q96hxXv7fv4yhAohqYrqc3liht+/L+9/13nKfES1o9lKmPZSUY2liD4FvU3NYl7ehcuI8PE+VS3aziZMijFY5ApaRJUWhCFrz2onI83E=
  matrix:
    secure: WxJUMspuImbaZBV4xeQflgioDdeNrlOhwiZwaPo63zzCSww8mJUR8RdmQaidTTsROXxqJ8Z2V6+NFF3DCkxcc0Vcew7BvRxWYjI5uX4jCyjAjkbF9wNFXmO+hagjvUOltL9gfKeehVze98yw43dLhEtoqCjb83gZb7ksF8P4NDysnN+IhTuZgV/9rkSDPibPb1CiHi/G/fK98d111HTNgj1aJyu5ctibydjyzSFslxDCuCE48EahhcPkqWOvtQD9v+GLvCL9ejCU0F/b8iK/FiR/jzKAlp6oxmN+jEump8FFZ/1tkxdbD8oZR5WQ3+c+niHAsK99ZtwO4IM5Zu0tGWhAfXus6Gm+L745u/9sjBBgkJ7Y0IR0EO/IiZc43YDbrBuaTCmXmY4aYbCkJtfmhRo+X3k6DE89zhQMyjCoLXX2pCvY/XTfvbjpH4VjlwNHxj080LcU6ReIfcpE8Gtu7yofcAGjpUPL1EwdtuxxBXh8pjHHAftR5De5aAbwzsaukowNiNkctgiZMylza/4IQtiRA59nKr/j2Ge+XxlUK1g4VIxm4PejqSCLoA1bZ3wHFaLwiZ87pmu89i7VgOYAT2AibywAmtg/rizvxT97tvI/ZVnZPQtxYvICcxgTQBZfDRAZGw2UCRcGghyaPTaW/0fz8mv6nBkZGCA+CF0AI+c=
