FROM nginx
ADD ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY dist/ /usr/share/nginx/html/
#EXPOSE 4200
#EXPOSE 80
#COPY nginx/nginx.conf /etc/nginx/nginx.conf
#EXPOSE 443
#CMD ["/usr/sbin/nginx", "-g", "daemon off;"]
